from operator import getitem
from ulauncher.api.client.Extension import Extension
from ulauncher.api.client.EventListener import EventListener
from ulauncher.api.shared.event import KeywordQueryEvent
from ulauncher.api.shared.item.ExtensionResultItem import ExtensionResultItem
from ulauncher.api.shared.action.RenderResultListAction import RenderResultListAction
from ulauncher.api.shared.action.OpenUrlAction import OpenUrlAction


class GnomeSessionExtension(Extension):
    def __init__(self):
        super(GnomeSessionExtension, self).__init__()
        self.subscribe(KeywordQueryEvent, KeywordQueryEventListener())


class KeywordQueryEventListener(EventListener):
    def on_event(self, event, extension):
        items = []
        options = [
            'AntiFraudAnalysisRequest-beta',
            'AntiFraudAnalysisRequest-prod',
            'AntiFraudUserInfo-beta',
            'AntiFraudUserInfo-prod',
            'AppConfig-beta',
            'AppConfig-prod',
            'ApprovalReports-beta',
            'ApprovalReports-prod',
            'ApprovalRequest-beta',
            'ApprovalRequest-prod',
            'B2BTransferBatch-beta',
            'B2BTransferBatch-prod',
            'BackupTestTable-beta',
            'BankConciliationBalance-beta',
            'BankConciliationBalance-prod',
            'BankDeposit-beta',
            'BankDeposit-prod',
            'BillingReport-beta',
            'BillingReport-prod',
            'Boleto-beta',
            'Boleto-prod',
            'BoletoPayment-beta',
            'BoletoPayment-prod',
            'BoletoPaymentEwallyPayment-beta',
            'BoletoPaymentEwallyPayment-prod',
            'BoletoPaymentReports-beta',
            'BoletoPaymentReports-prod',
            'CashbackItems-beta',
            'CashbackItems-prod',
            'CashbackPaymentTransactions-beta',
            'CashbackPaymentTransactions-prod',
            'CashbackPayments-beta',
            'CashbackPayments-prod',
            'CashbackReports-beta',
            'CashbackReports-prod',
            'CellPhoneProblems-beta',
            'CellPhoneProblems-prod',
            'CellPhoneProducts-beta',
            'CellPhoneProducts-prod',
            'CellPhoneRechargeReports-beta',
            'CellPhoneRechargeReports-prod',
            'CellPhoneRecharges-beta',
            'CellPhoneRecharges-prod',
            'CoinVault-beta',
            'Correspondent-beta',
            'Correspondent-prod',
            'CorrespondentCommission-beta',
            'CorrespondentCommission-prod',
            'CorrespondentCommissionReports-beta',
            'CorrespondentCommissionReports-prod',
            'CreditCard-beta',
            'CreditCard-prod',
            'CreditCardCipData-beta',
            'CreditCardCipData-prod',
            'CreditCardEventJob-beta',
            'CreditCardEventJob-prod',
            'CreditCardLiquidation-beta',
            'CreditCardLiquidation-prod',
            'CreditCardNotAuthorized-beta',
            'CreditCardNotAuthorized-prod',
            'CreditCardPayment-beta',
            'CreditCardPayment-prod',
            'CreditCardPayments-beta',
            'CreditCardPayments-prod',
            'CreditCardPhysicalMerchant-beta',
            'CreditCardPhysicalMerchant-prod',
            'CreditCardPos-beta',
            'CreditCardPos-prod',
            'CreditCardReceivable-beta',
            'CreditCardReceivable-prod',
            'CreditCardReceivableConciliationFiles-beta',
            'CreditCardReceivableConciliationFiles-prod',
            'CreditCardReceivableContractEffect-beta',
            'CreditCardReceivableContractEffect-prod',
            'CreditCardReceivableFragment-beta',
            'CreditCardReceivableFragment-prod',
            'CreditCardReceivableLiquidation-beta',
            'CreditCardReceivableLiquidation-prod',
            'CreditCardReceivableNotification-beta',
            'CreditCardReceivableNotification-prod',
            'CreditCardReceivablePayment-beta',
            'CreditCardReceivablePayment-prod',
            'CreditCardReceivablePaymentCopy-prod',
            'CreditCardReceivableRecord-beta',
            'CreditCardReceivableRecord-prod',
            'CreditCardReceivableReport-beta',
            'CreditCardReceivableReport-prod',
            'CreditCardReceivableSnapshot-beta',
            'CreditCardReceivableSnapshot-prod',
            'CreditCardReportItems-beta',
            'CreditCardReportItems-prod',
            'CreditCardReports-beta',
            'CreditCardReports-prod',
            'CreditCards-beta',
            'CreditCards-prod',
            'CsfInterfacePrivateKeys-beta',
            'CsfInterfacePrivateKeys-prod',
            'DynamoTestTable-beta',
            'DynamoTestTable1-beta',
            'DynamoTestTable2-beta',
            'Ecard-beta',
            'Ecard-prod',
            'EcardAccount-beta',
            'EcardAccount-prod',
            'EcardBatch-beta',
            'EcardBatch-prod',
            'EcardProduct-beta',
            'EcardProduct-prod',
            'EcardStock-beta',
            'EcardStock-prod',
            'EcardTransactionsDisputes-beta',
            'EguardianCollectorErrors-beta',
            'EguardianCollectorErrors-preprod',
            'EguardianCollectorErrors-prod',
            'EguardianCollectorFlows-beta',
            'EguardianCollectorFlows-preprod',
            'EguardianCollectorFlows-prod',
            'ExternalEvaluation-beta',
            'ExternalEvaluation-prod',
            'FinancialRoutinesInputFiles-beta',
            'FinancialRoutinesInputFiles-prod',
            'GatewayBillings-beta',
            'GatewayBillings-prod',
            'GatewayBoleto-beta',
            'GatewayBoleto-prod',
            'GatewayContract-beta',
            'GatewayContract-prod',
            'GatewayCreditCardPayment-beta',
            'GatewayCreditCardPayment-prod',
            'GatewayCreditCardPaymentAdvance-beta',
            'GatewayCreditCardPaymentAdvance-prod',
            'GatewayUserCard-beta',
            'GatewayUserCard-prod',
            'InternalProcessRecords-beta',
            'InternalProcessRecords-prod',
            'KycReport-beta',
            'KycReport-prod',
            'Marketplace-beta',
            'Marketplace-prod',
            'MarketplaceOrder-beta',
            'MarketplaceOrder-prod',
            'MarketplaceSeller-beta',
            'MarketplaceSeller-prod',
            'MultibankTransfer-beta',
            'MultibankTransfer-prod',
            'Notification-beta',
            'Notification-prod',
            'NotificationEvent-beta',
            'NotificationEvent-prod',
            'NotificationSocketSession-beta',
            'NotificationSocketSession-prod',
            'Offboarding-beta',
            'Offboarding-prod',
            'Onboarding-beta',
            'Onboarding-prod',
            'OnboardingEmailConfirmation-beta',
            'OnboardingEmailConfirmation-prod',
            'PixChangeLimitsRequest-beta',
            'PixChangeLimitsRequest-prod',
            'PixClaim-beta',
            'PixClaim-prod',
            'PixContacts-beta',
            'PixContacts-prod',
            'PixDevolutions-beta',
            'PixInfraction-beta',
            'PixInfraction-prod',
            'PixJwsKeys-beta',
            'PixJwsKeys-prod',
            'PixKey-beta',
            'PixKey-prod',
            'PixKeyCache-beta',
            'PixKeyCache-prod',
            'PixKeySearchRecord-beta',
            'PixKeySearchRecord-prod',
            'PixKeyVerification-beta',
            'PixKeyVerification-prod',
            'PixQrCode-beta',
            'PixQrCode-prod',
            'PixRefunds-beta',
            'PixRefunds-prod',
            'PixServicesAvailability-beta',
            'PixServicesAvailability-prod',
            'PixTransaction-beta',
            'PixTransaction-prod',
            'PixUserBucket-beta',
            'PixUserBucket-prod',
            'Problems-beta',
            'Problems-prod',
            'RdstationToken-beta',
            'ReissueEventJob-beta',
            'ReissueEventJob-prod',
            'Reports-beta',
            'Reports-prod',
            'ReportsScheduleConfig-beta',
            'ReportsScheduleConfig-prod',
            'RestrictedPeople-beta',
            'RestrictedPeople-prod',
            'RestrictiveListInternal-beta',
            'RestrictiveListInternal-prod',
            'ScheduledJob-beta',
            'ScheduledJob-prod',
            'SubAcquirers-beta',
            'SubAcquirers-prod',
            'SuspiciousDataIndex-beta',
            'SuspiciousDataIndex-prod',
            'TopazioAccount-beta',
            'TopazioAccount-prod',
            'TopazioStatement-beta',
            'TopazioStatement-prod',
            'TopazioTransfer-beta',
            'TopazioTransfer-prod',
            'TopazioTransferCopy-beta',
            'TopazioTransferCopy-prod',
            'TransitCardConciliation-beta',
            'TransitCardConciliation-prod',
            'TransitCardFavorites-beta',
            'TransitCardFavorites-prod',
            'TransitCardRecharges-beta',
            'TransitCardRecharges-prod',
            'UserConfigs-beta',
            'UserConfigs-prod',
            'UserConnectionInfo-beta',
            'UserConnectionInfo-prod',
            'UserDevices-beta',
            'UserDevices-prod',
            'UserEnrichedData-beta',
            'UserEnrichedData-prod',
            'UserGroup-beta',
            'UserGroup-prod',
            'UserLoginToken-beta',
            'UserLoginToken-prod',
            'UserManagement-beta',
            'UserManagement-prod',
            'UserManagementJob-beta',
            'UserManagementJob-prod',
            'UserMfa-beta',
            'UserMfa-prod',
            'UserPasswordRecovery-beta',
            'UserPhone-beta',
            'UserPhone-prod',
            'UserPhoneIndex-beta',
            'UserPhoneIndex-prod',
            'UserPrivateKeys-beta',
            'UserPrivateKeys-prod',
            'UserReapprovalJob-beta',
            'UserReapprovalJob-prod',
            'UserRecovery-beta',
            'UserRecovery-prod',
            'UserRole-beta',
            'UserRole-prod',
            'UserSession-beta',
            'UserSession-prod',
            'UserUpload-beta',
            'UserUpload-prod',
            'VotorantimTransaction-beta',
            'VotorantimTransaction-prod',
            'Workdays-beta',
            'Workdays-prod',
            'XapoEcard-beta',
            'XapoEcard-prod',
            'XapoEvent-beta',
            'XapoEvent-prod',
            'XapoExchange-beta',
            'XapoExchange-prod',
            'XapoMessage-beta',
            'XapoMessage-prod',
            'XapoOrder-beta',
            'XapoOrder-prod',
            'XapoPaymentNotification-beta',
            'XapoPaymentNotification-prod',
            'XapoReport-beta',
            'XapoReport-prod',
            'XapoUser-beta',
            'XapoUser-prod',
            'XapoUserApproval-beta',
            'XapoUserApproval-prod',
            'cepBR-beta',
        ]
        my_list = event.query.split(" ")
        if len(my_list) == 1:
            for tableName in options:
                items.append(getitem(tableName))
            return RenderResultListAction(items)


def getItem(tableName):
    return ExtensionResultItem(icon='images/icon.png',
                               name='AWS API Gateway',
                               description='AWS API Gateway',
                               on_enter=OpenUrlAction("https://www.youtube.com/%s" % tableName))


if __name__ == '__main__':
    GnomeSessionExtension().run()
